name: Buf CI
on:
  push:
    paths:
      - "schema/proto/**/*.proto"

permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Buf CLIのインストールなど
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # buf lintの実行
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "schema/proto"
